### ISSUE TITLE
生成的表格没有按照size的大小排序

### ISSUE THREAD

**Issue by hanlei1786** [gupeng1978/tools#1]
- cfg内容：
```yaml
excel_path: '../data/dual_edge10_pcie_perf.xlsx' # 输出的excel表格路径
sheets:
  tag: [dual_edge10_rpc, dual_edge10_datacopy] #excel表格sheet名称
tables:
 # 表1
  - sheet_tag: dual_edge10_rpc
    name: "#pcie_rpc"
    head-0: [env, ave_cost, speed]
    head-key: [] # 列方向上排序且合并
    alias: # 表头的别名，支持中文转译
      "env": "测试环境"
      "ave_cost": "平均耗时(us)"
      "speed": "带宽(MB/s)"
    record_file : '../data/dual_edge10_pcie_perf.log' # #pcie_rpc: (env@dev0),(ave_cost@50),(speed@100)
  # 表2
  - sheet_tag: dual_edge10_datacopy
    name: "#pcie_datacopy"
    head-0: [env, ifPara, ifTwoDevice, memtype, size, direction, speed]
    head-key: [env, ifPara, ifTwoDevice, memtype, size] # 列方向上排序且合并
    alias: # 表头的别名，支持中文转译
      "env": "测试环境"
      "ifPara": "h2d/d2h是否并行"
      "ifTwoDevice": "是否2个device同时"
      "memtype": "device内存类型"
      "size": "传输大小"
      "direction": "传输方向"
      "speed": "带宽(MB/s)"
    record_file : '../data/dual_edge10_pcie_perf.log' # #pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@1K),(direction@h2d),(speed@100)
```

- log内容：
```log
#pcie_rpc: (env@dev0),(ave_cost@68.847500),(speed@1.135863)
#pcie_rpc: (env@dev1),(ave_cost@68.857500),(speed@1.135698)

#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@1K),(direction@h2d),(speed@4.982462)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@1K),(direction@d2h),(speed@5.033827)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@4K),(direction@h2d),(speed@19.531250)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@4K),(direction@d2h),(speed@19.629397)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@64K),(direction@h2d),(speed@217.770035)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@64K),(direction@d2h),(speed@217.770035)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@512K),(direction@h2d),(speed@491.159136)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@512K),(direction@d2h),(speed@502.008032)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@1024K),(direction@h2d),(speed@548.546352)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@1024K),(direction@d2h),(speed@638.977636)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@4096K),(direction@h2d),(speed@725.952813)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@4096K),(direction@d2h),(speed@777.151739)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@8192K),(direction@h2d),(speed@770.787166)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@8192K),(direction@d2h),(speed@797.050912)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@32768K),(direction@h2d),(speed@785.951124)
#pcie_datacopy: (env@dev0),(ifPara@0),(ifTwoDevice@0),(memtype@0),(size@32768K),(direction@d2h),(speed@794.853325)
```

- 生成表格：
![image](https://github.com/gupeng1978/tools/assets/143069566/b5042ed6-8688-4f9d-b0e8-d95ee32005ae)

- 期望：表格数据按照传输大小升序显示
