### ISSUE TITLE
excel列字母名称未正确转换

### ISSUE THREAD

**Issue by gaopeng1965** [gupeng1978/tools#4]
![image](https://github.com/gupeng1978/tools/assets/42139408/ab3eec63-da2a-4d94-b28a-cc407d3f3402)
超过Z列的转换不正确。

**Comment by gupeng1978** [comment]
# 测试case 构建
##  sample7配置
```
excel_path: 'sample7.xlsx' # 输出的excel表格路径
sheets:
  tag: [sheet1] #excel表格sheet名称
tables:
  # 表1
  - sheet_tag: sheet1 # 这个表属于sheet1
    name: "%tab1" # 该表的records记录在path/to/table1.log中以%tab1为关键字的行中
    head-0: [A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,AA]   #一级表头(不支持中文)
    head-1: [A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,AA]  #二级表头(不支持中文), 长度必须和一级表头相等
    head-key: [A] # 列方向上以X1排序且合并    
    record_file: 'sample7.log' # log记录，每行最多一个record记录，格式为 ...%tab1...(X1@2.0)...(X2@3)...(Y@content1)...(Z@content2)
```
## log
```
%tab1: (A@1), (B@2), (C@3), (D@4),(E@1), (F@2), (G@3), (H@1), (I@2), (J@3), (K@1), (L@2), (M@3), (N@1), (O@2), (P@3), (Q@1), (R@2), (S@3), (T@1), (U@2), (V@3), (W@1), (X@2), (Y@3), (Z@1),(AA@1),
```

# Debug调试
该case会报错, 出现../python3.8/site-packages/openpyxl/utils/cell.py,

```
def column_index_from_string(str_col):
    """Convert a column name into a numerical index
    ('A' -> 1)
    """
    # we use a function argument to get indexed name lookup
    try:
        return _COL_STRING_CACHE[str_col.upper()]
    except KeyError: # 出错,此处str_col为字符串'['
        raise ValueError("{0} is not a valid column name".format(str_col))
```
传递给openyxl的header字符为'A', 'B'...'Z', 'AA',  而ASCII字符表中'Z'后面的字符为'[', 此处为openpyxl对字符转换出现bug, 把紧跟着'Z'后面的字符串'AA' 错误翻译为'['.

# 结论
该Bug属于三方库openpyxl的bug, 目前无法修复, 只能使用上约束: column列的数目不能超过26个.
@gaopeng1965
